# Generated by Django 5.2.5 on 2025-09-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('complete', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=300, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_updation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
